# Generated by Django 4.0 on 2022-10-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_player',
            name='payment_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_player',
            name='payment_due_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_player',
            name='player_batting_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_player',
            name='player_bowling_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_player',
            name='player_over',
            field=models.IntegerField(null=True),
        ),
    ]
