# Generated by Django 4.0 on 2022-10-18 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player_number_alter_match_player_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_player',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='match_player',
            name='payment_due_amount',
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
    ]
