# Generated by Django 4.0 on 2022-10-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_match_player_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
