# Generated by Django 4.0 on 2022-10-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_fund_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='amount_paid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
