# Generated by Django 4.1.2 on 2022-11-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking_booking_player_expense_ground_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
