# Generated by Django 4.1.2 on 2022-11-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2022-10-8'),
            preserve_default=False,
        ),
    ]
