# Generated by Django 4.1.2 on 2022-11-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tagline',
            field=models.CharField(default='bowler', max_length=50),
            preserve_default=False,
        ),
    ]
