# Generated by Django 4.1.2 on 2022-11-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_booking_player_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_player',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
